### ISSUE TITLE
[Question] have you tried your script on macOS system ?

### ISSUE THREAD

**Issue by sen0rxol0** [Hacktivation/iOS-Hacktivation-Toolkit#1]

**Comment by sen0rxol0** [comment]
i will be testing it on macOS Catalina, cheers.

**Comment by Hacktivation** [comment]
Let me know how it's goes 
-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


14 Jun 2020, 21:13 by notifications@github.com:

**Comment by johnponflanchan** [comment]
This won't work automatically with macOS because you need to change some things to make it macOS compatible. and even then, I strongly don't recommend Catalina for this.

**Comment by sen0rxol0** [comment]
You can delete this now. Thanks to @johnponflanchan
