### ISSUE TITLE
Ipad 7 14.7.1

### ISSUE THREAD

**Issue by Joglezbee1** [Hacktivation/iOS-Hacktivation-Toolkit#21]
Hello someone please help me come to my senses here, I have been stuck on this for hours I purchased a device from goodwill auction website that was icloud locked and I first went through apple provided my proof of purchase and they said no they need original reciept so I asked if they would contact owner or give me owner information to contact and they said no. I found this and I started by doing a full install after that i tried to use checkra1n to jailbreak and kept getting error -66 replug device in. Wont work I tried to doenload untethered patch and I keep getting unplug and replug device in. The only thing that works is restoreing device on the menu. I have spent hours trying to figure this out. If someone is willing to help me I will literally pay them. I have alot of money and tome invested into this ipad it was a gift for my fiancee and now im stick and i do not want to have to throw device away but i dont know what else to do. If someone will help me troubleshoot this problem or walk me througb it I would be forever grateful.

**Comment by Joglezbee1** [comment]
Okay so I figured out how to bypass device with some trial and error, I realize that there is no way to sign into icloud but is there a way for me to actually see the email or any information of icloud owner so I can try and comtact him to have him remove lock? If not im looking into the oce4n bypass but theres little information on it. I would much perfer to be able to contact owner of device and have him simply remove lock but apple are dicks and wont tell me his email

**Comment by dinnob** [comment]
> Okay so I figured out how to bypass device with some trial and error, I realize that there is no way to sign into icloud but is there a way for me to actually see the email or any information of icloud owner so I can try and comtact him to have him remove lock? If not im looking into the oce4n bypass but theres little information on it. I would much perfer to be able to contact owner of device and have him simply remove lock but apple are dicks and wont tell me his email 

Try pressing the power button multiple times quickly to reveal the device emergency info. It works great on iPhones

**Comment by Joglezbee1** [comment]
Tried that nothing comes up, does anyone know if tethered paid version works?

**Comment by dinnob** [comment]
> Tried that nothing comes up, does anyone know if tethered paid version works?

Say Hi on this email dbwiteless@yahoo.com 

I might help

**Comment by Joglezbee1** [comment]
How,?

**Comment by cpablast** [comment]
You knowingly purchased an icloud locked device?? You are better off trying checkm8, mina, emc or iremove to try and bypass it... Apple will never give you the owners email, even if you have the original receipt but are not the one who bought the device from them, they might choose not to help you.. Basically you are 80% screwed

**Comment by Joglezbee1** [comment]
Yeah I figured that i could contact apple with proof of purchas. But that
didn't work as planned lol just didn't want to have to throw it away

J Oglesbee

**Comment by Joglezbee1** [comment]
If it comes down to it I will just throw the device away over reselling it
but honestly I just want to try and get the original owners email so I can
try and contact him get the device removed from his account instead of
trying to bypass it

J Oglesbee
